const functions = require("firebase-functions");
const admin = require('firebase-admin');
const { initializeApp } = require("firebase-admin/app");

const { saveAttendance } = require("./api/teacher/attendance.js");
const { getAllStudentsfromClass, getCalendar } = require("./api/common/teacher.js");
const { saveMarks } = require("./api/teacher/savemarks.js");
const { getClass } = require("./api/common/getclass.js");
const { getAllTests, createNewTest } = require("./api/teacher/getAllTests.js");
const { fetchEvents,deleteEventById } = require("./api/common/fetchEvents.js");
const { uploadFile, getAssignments } = require("./api/common/assignments.js");
const {createUserIdsWithExcelFile,createClasses,getClasses,getUsersByClassOrSchool,createUsersWithId, getDashboard} = require("./api/admin/admin.js");
const {createAnnouncements} = require("./api/admin/createAnnouncements.js");
const { addHoliday } = require("./api/admin/addHoliday.js");
const { student_exam } = require("./api/common/student_exam.js");
const { subject } = require("./api/common/subject.js");
const { getExamsByClassId, createNewExam } = require("./api/common/examination.js");
const { uploadImage, getImages} = require("./api/admin/FileUpload.js");
const { getQuizzesByClassTeacherSubject } = require("./api/common/Quiz.js");


exports.saveAttendance = functions.https.onRequest(saveAttendance);
exports.saveMarks = functions.https.onRequest(saveMarks);
exports.getAllStudentsfromClass = functions.https.onRequest(getAllStudentsfromClass);
exports.getClass = functions.https.onRequest(getClass);
exports.getAllTests = functions.https.onRequest(getAllTests);
exports.createNewTest = functions.https.onRequest(createNewTest);
exports.fetchEvents = functions.https.onRequest(fetchEvents);
exports.getCalendar = functions.https.onRequest(getCalendar);
exports.uploadFile = functions.https.onRequest(uploadFile);
exports.getAssignments = functions.https.onRequest(getAssignments);
exports.createUserIdsWithExcelFile = functions.https.onRequest(createUserIdsWithExcelFile);
exports.createClasses = functions.https.onRequest(createClasses);
exports.getClasses = functions.https.onRequest(getClasses);
exports.createAnnouncements = functions.https.onRequest(createAnnouncements); 
exports.getUsersByClassOrSchool = functions.https.onRequest(getUsersByClassOrSchool);
exports.createUsersWithId = functions.https.onRequest(createUsersWithId);
exports.getDashboard = functions.https.onRequest(getDashboard);
exports.addHoliday = functions.https.onRequest(addHoliday);
exports.getExamsByClassId = functions.https.onRequest(getExamsByClassId);
exports.student_exam = functions.https.onRequest(student_exam);
exports.subject = functions.https.onRequest(subject);
exports.createNewExam = functions.https.onRequest(createNewExam);
exports.uploadImage = functions.https.onRequest(uploadImage);
exports.getImages = functions.https.onRequest(getImages);
exports.deleteEventById = functions.https.onRequest(deleteEventById);
exports.getQuizzesByClassTeacherSubject = functions.https.onRequest(getQuizzesByClassTeacherSubject);
admin.initializeApp();