GET http://127.0.0.1:5001/edge-2060b/us-central1/saveAttendance
Content-Type: application/json

[
  {
    "participantId": "participantId1",
    "attendanceStatus": "present"
  },
  {
    "participantId": "participantId2",
    "attendanceStatus": "absent"
  },
  {
    "participantId": "participantId3",
    "attendanceStatus": "present"
  }
]
############
GET http://127.0.0.1:5001/edge-2060b/us-central1/getAllStudentsfromClass
Content-Type: application/json

{
    "Type":"student",
    "Class":"8",
    "Section":"A",
    "School":"aps"

}
###############################################
GET http://127.0.0.1:5001/edge-2060b/us-central1/saveMarks
Content-Type: application/json

[
{
  "uid":"1",
  "subject":"science",
  "marks":"70"  
}
]

############################################

GET http://127.0.0.1:5001/edge-2060b/us-central1/getClass
Content-Type: application/json

  {
    "uid":"1690DBPBC1MVp3y9Ez04Exony4V2",
  }

#################################
GET http://127.0.0.1:5001/edge-2060b/us-central1/marksofclass
Content-Type: application/json

[
{
            "uid":"11690DBPBC1MVp3y9Ez04Exony4V2",
            "className":"8",
            "classCode":"A"
}
]

###############
GET http://127.0.0.1:5001/edge-2060b/us-central1/getAllTests
Content-Type: application/json

{
            "teacherId":"11690DBPBC1MVp3y9Ez04Exony4V2",
            "classId":"E1wuTQmnaMp8oW0bvIPB"
}

{
    "uid":"1690DBPBC1MVp3y9Ez04Exony4V2"
}

########################################
POST http://127.0.0.1:5001/edge-2060b/us-central1/getAllTests
Content-Type: application/json

{
    "teacherId":"1690DBPBC1MVp3y9Ez04Exony4V2",
    "classId":"E1wuTQmnaMp8oW0bvIPB"
}

#############################
POST http://127.0.0.1:5001/edge-2060b/us-central1/fetchEvents
Content-Type: application/json

{
  "school": "aps"
}