GET http://127.0.0.1:5001/edge-2060b/us-central1/saveAttendance
Content-Type: application/json

[
  {
    "participantId": "participantId1",
    "attendanceStatus": "present"
  },
  {
    "participantId": "participantId2",
    "attendanceStatus": "absent"
  },
  {
    "participantId": "participantId3",
    "attendanceStatus": "present"
  }
]
############
GET http://127.0.0.1:5001/edge-2060b/us-central1/getAllStudentsfromClass
Content-Type: application/json

{
    "Type":"student",
    "Class":"8",
    "Section":"A",
    "School":"aps"

}
##########################################
GET http://127.0.0.1:5001/edge-2060b/us-central1/saveMarks
Content-Type: application/json

[
{
  "uid":"1",
  "subject":"science",
  "marks":"70"  
}
]
########################################
POST https://us-central1-edge-2060b.cloudfunctions.net/getAllStudentsfromClass
Content-Type: application/json

{
    "Type":"student",
    "Class":"8",
    "Section":"A",
    "School":"aps"
}