POST https://us-central1-edge-2060b.cloudfunctions.net/getCalender
Content-Type: application/json

{
    "School":"aps"
}
################################
POST http://127.0.0.1:5001/edge-2060b/us-central1/uploadFile

################################################################
GET http://127.0.0.1:5001/edge-2060b/us-central1/saveAttendance
Content-Type: application/json

[
  {
    "uid": "participantId1",
    "attendanceStatus": "present"
  },
  {
    "uid": "participantId2",
    "attendanceStatus": "absent"
  },
  {
    "uid": "participantId3",
    "attendanceStatus": "present"
  }
]
#################
GET http://127.0.0.1:5001/edge-2060b/us-central1/getAllStudentsfromClass
Content-Type: application/json

{
    "Type":"student",
    "Class":"8",
    "Section":"A",
    "School":"aps",
    "purpose":"attendance",
    "teacherID": "1690DBPBC1MVp3y9Ez04Exony4V2"
}
###############################################
GET http://127.0.0.1:5001/edge-2060b/us-central1/saveMarks
Content-Type: application/json

[
{
  "uid":"1",
  "subject":"science",
  "marks":"70"  
}
]

############################################

GET http://127.0.0.1:5001/edge-2060b/us-central1/getClass
Content-Type: application/json

  {
    "uid":"1690DBPBC1MVp3y9Ez04Exony4V2",
  }

#################################
GET http://127.0.0.1:5001/edge-2060b/us-central1/marksofclass
Content-Type: application/json

[
{
            "uid":"11690DBPBC1MVp3y9Ez04Exony4V2",
            "className":"8",
            "classCode":"A"
}
]

###############
GET http://127.0.0.1:5001/edge-2060b/us-central1/getAllTests
Content-Type: application/json

{
            "teacherId":"11690DBPBC1MVp3y9Ez04Exony4V2",
            "classId":"E1wuTQmnaMp8oW0bvIPB"
}

{
    "uid":"1690DBPBC1MVp3y9Ez04Exony4V2"
}

########################################
POST http://127.0.0.1:5001/edge-2060b/us-central1/getAllTests
Content-Type: application/json

{
    "teacherId":"1690DBPBC1MVp3y9Ez04Exony4V2",
    "classId":"E1wuTQmnaMp8oW0bvIPB"
}

#############################
POST http://127.0.0.1:5001/edge-2060b/us-central1/fetchEvents
Content-Type: application/json

{
  "school": "aps"
}

################################
POST https://us-central1-edge-2060b.cloudfunctions.net/createNewTest
Content-Type: application/json

{
        "classId": "classId",
        "teacherId": "user",
        "testName": "testName",
        "subject": "subject",
        "date": "date"
};

############
POST http://127.0.0.1:5001/edge-2060b/us-central1/deleteRecordsByDate
Content-Type: application/json

{
    "date": "2024-03-10"

}

#####################
POST http://127.0.0.1:5001/edge-2060b/us-central1/addHoliday
Content-Type: application/json

{
  "schoolId": "poyMxpKXvhHaPNdXpSwx",
  "date": "2024-05-25",
  "day": "Sushant Jayanti"
}

#####################
POST http://127.0.0.1:5001/edge-2060b/us-central1/student_exam
Content-Type: application/json

{

 "classId": "oXDtq0AKksvGmiHvqktQ"

}
##################################
POST http://127.0.0.1:5001/edge-2060b/us-central1/subject
Content-Type: application/json

{

  "schoolId": "poyMxpKXvhHaPNdXpSwx",
  "subjectNames": ["Maths", "English", "Science"]

}